source "https://rubygems.org"

#gem "jekyll", "~> 4.2.2"



group :jekyll_plugins do
  gem 'just-the-docs'
  gem "jekyll-feed"
  gem "github-pages"
  gem 'jekyll-seo-tag'
end


# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

gem "webrick", "~> 1.7"


